### ISSUE TITLE
Mean ROC curve in ggroc()

### ISSUE THREAD

**Issue by AngCamp** [xrobin/pROC#123]
It would be very nice if the package contained a means of producing a mean ROC curve from a list of roc objects.  This stack post illustrates the desired output.  Sklearn in python can do this quite easily as well, as well as plotting the S.D. along the curve as well.

https://stackoverflow.com/questions/52467915/plotting-mean-roc-curve-for-multiple-roc-curves-r

**Comment by xrobin** [comment]
I assume this is the same as the request in  #41?

**Comment by AngCamp** [comment]
Sort of, except the visualization they show should be smoother.  I have provided the sklearn version above which you should take a look at.  Another issue I've noticed and this prehaps should be a seperate bug issue, is that the ROC curve is sometimes plotting diagonal lines.  This absolutely should not happen.

This plot is made using your ggroc() function from a list of roc objects:
![image](https://github.com/xrobin/pROC/assets/77176433/e461b818-85e8-431e-8c36-fc039555da8a)
 
It should not be displaying diagonal interpolations between cuts.  There should be steps occurring.

**Comment by xrobin** [comment]
I don't know what you mean by they should be smoother. Of course if you average many curve the result will be smoother, but this is given by the averaging itself.

By the way diagonal lines in ROC curves are 100% normal.

**Comment by AngCamp** [comment]
Smoother CI:  The blocks of CI are not a very nice solution IMO, if you look at the sklearn method they show the CI as a blurred or shaded area displaying the error bars across the whole plot.  Here is an example of this in ggplot2: https://stackoverflow.com/questions/26396149/custom-ggplot2-shaded-error-areas-on-categorical-line-plot 

Diagonal Interpolation:  I am only passing on a complaint from my supervisor, he's not wrong either.  I think he is being nitpicky but it isn't invalid criticism. If you think about what the ROC is it should only grow in steps, as the threshold is increased it does not result in smooth FPR or FNR changes, it jumps as the classification of the datapoints changes.  With lots of data it will look smoother since the steps will be smaller but in reality small discrete jumps are occurring.   I appreciate that the diagonals are just a result of interpolating between two datapoints but in this case it is technically incorrect.    If you look at any other ROC plotting package in R they do not plot the ROC like that because it's technically incorrect.
https://cran.r-project.org/web/packages/plotROC/vignettes/examples.html 

The ROC curve should be a sawtoothed curve, no graded continuous changes should be present because it jumps in discrete steps.

**Comment by xrobin** [comment]
This is getting out of hand. You're asking about mean which should be smooth, but now suddenly confidence intervals are coming into the picture.  You're linking to stack overflow posts which do things but I don't know which part you're referring to. Ultimately I have no clear idea what you're after exactly. Please be very clear and precise with what you'd like, what algorithm should be used, how it should be displayed, etc. Otherwise I'll have to close this one as unclear.

Diagonals are the correct way to handle ties as per ROC definition, see [Fawcett's An introduction to ROC analysis](https://ccrma.stanford.edu/workshops/mir2009/references/ROCintro.pdf). I don't care what your supervisor is thinking, breaking ties other than with the expected segment is wrong. The plotROC package does that too, as expected and as appropriate.
