### ISSUE TITLE
Calculate auc in pROc

### ISSUE THREAD

**Issue by anka0501** [xrobin/pROC#32]
I'm trying to calculate auc based on a pROC package. I use the formula:

auc(set_temp$def_woe,set_temp$total_pymnt_woe)

Unfortunately, for some variables, I getting an error:  
Error in if (thresholds[tie.idx] == unique.candidates[tie.idx -1]) { : argument is of length zero

**Comment by xrobin** [comment]
Do you have infinite values in the `predictor` variable? `any(is.infinitie(set_temp$total_pymnt_woe))`. 
If so we're looking at issue #30. Otherwise, can you please identify which variable is causing this error and isolate a reproducible example?

**Comment by anka0501** [comment]
Thanks for the answer. My predictor variable has infinite values. So probably that's why the error appeared. I realized that this code worked on the older version of R. I reinstalled R from the version 3.5 to 3.4 and it works.

**Comment by xrobin** [comment]
This has nothing to do with the version of R, only that of pROC. The current error message is meaningless and I apologize about it. But versions prior to 1.12 could produce invalid ROC curves instead (ie. not reaching 0 or 100% sensitivity or specificity). V. 1.12 still does in some cases.

Version 1.13 in preparation will reject infinite values as described in issue #30, with a meaningful error message.  This is because infinities cannot be thresholded properly from -Inf to +Inf as is required for ROC analysis. If you have infinite values in your predictor I suggest you find a way to replace them by finite values.
