### ISSUE TITLE
Error in delongPlacementsCpp(roc) : function 'Rcpp_precious_remove' not provided by package 'Rcpp'

### ISSUE THREAD

**Issue by mathiasS-hub** [xrobin/pROC#99]
Hi @xrobin 
When I run the roc funtion I get the error "Error in delongPlacementsCpp(roc) : function 'Rcpp_precious_remove' not provided by package 'Rcpp' ".

library(pROC)
glm.fit=glm(Outcome~S4v1+Age+SEX, family = binomial(link = "logit"), data=df)
roc1 <-roc(df$Outcome, glm.fit$fitted.values, plot=TRUE, legacy.axes=TRUE,
    percent =FALSE, main="Prediction of S4 status",  xlab="FalSE Positive Rate",
    ylab="True Positive Rate", col="red", lwd=3, print.auc=TRUE, ci=TRUE)

Error in delongPlacementsCpp(roc) : 
  function 'Rcpp_precious_remove' not provided by package 'Rcpp'

Please advise on how I can overcome this. 
Cheers,
Mathias

**Comment by xrobin** [comment]
This typically happens after an Rcpp update. Please install the latest versions of both pROC and Rcpp.

See also [This thread on stack overflow](https://stackoverflow.com/questions/68416435/rcpp-package-doesnt-include-rcpp-precious-remove).

Feel free to reopen the issue if the problem persists.

**Comment by mathiasS-hub** [comment]
Hi Xavier,
We had already installed the latest versions of both pROC and Rcpp and the
error persisted.
Cheers,
Mathias

**Comment by CanWood** [comment]
Hey folks,
As an administrator of the system that Mathias was using while having this issue, I just wanted to post a bit more detail about this one in case anyone else has similar issues.  A new version of Rcpp had been installed with `BiocManager::install("Rcpp", force = TRUE )` followed by a fresh pROC with `BiocManager::install("pROC", force = TRUE )` before this issue was submitted so we were on latest and Mathias was still having an issue.

The cause of the continued error was that he had a personal `~/R/x86_64-pc-linux-gnu-library/4.0/Rcpp` installed which was older and taking precedence.   Deleting that folder resolved the issue.

Cheers
Scott
